### ISSUE TITLE
docs must include reference to Gemfile

### ISSUE THREAD

**Issue by apla** [jirutka/rake-jekyll#2]
for those, who don't know ruby at all

**Comment by jirutka** [comment]
Could you please be more specific what it’s missing in the current documentation?

**Comment by apla** [comment]
I tried instruction you provided, step by step. After push to the repository, Travis gives me errors, `Gemfile not found`, `rake-jekyll not found` and so on. So, my Gemfile (seems basic one) is:

```
source 'https://rubygems.org'

gem "rake"
gem "jekyll"
gem "rake-jekyll"
```

**Comment by apla** [comment]
Excluding this one moment, instruction is very good and detailed.
