### ISSUE TITLE
jekyll build failure does not cause rake task to fail

### ISSUE THREAD

**Issue by travi** [jirutka/rake-jekyll#3]
The [system call](https://github.com/jirutka/rake-jekyll/blob/master/lib/rake-jekyll/git_deploy_task.rb#L170) does not use the exit code to fail the rake task. 

I was able to work around this issue with a [simple change](https://github.com/travi/matt.travi.org/commit/dc9b050d2fe20f4fc0803c035a801ab1f09b4610), but thought you may want to handle this in the gem itself.

**Comment by razor-x** [comment]
I noticed this issue a bit after my original post on deploying this way. Anyway I switched from using the `system` call to the `sh` method which seems to be the preferred way for rake. The `sh` method should fail the rake task correctly and give the correct exit code.

See https://gist.github.com/razor-x/8166421

**Comment by jirutka** [comment]
@razor-x I know about the `sh` method, but the problem is that this method is defined by rake and it's not available inside a lambda IIRC. That's why I used `system` instead.
