### ISSUE TITLE
.nojekyll addition

### ISSUE THREAD

**Issue by johncarl81** [jirutka/rake-jekyll#4]
I am having a problem with my non-gh_pages branch being built by travis after the content has been published to it:
https://github.com/johncarl81/johncarl81.github.io
https://travis-ci.org/johncarl81/johncarl81.github.io/builds

What do you think about adding the `.nojekyll` file to the generated site directory?

**Comment by mwiley** [comment]
You can add something like

```
branches:
  only: jekyll
```

or 

```
branches:
  except: master
```

to .travis.yml.

**Comment by johncarl81** [comment]
My master branch doesn't contain a `.travis.yml` file.  will this still work?

**Comment by mwiley** [comment]
Yes.

**Comment by johncarl81** [comment]
Hmm, just tried it with the configuration:

```
branches:
  only: site
```

https://github.com/johncarl81/johncarl81.github.io/commit/e62fad632a85a99d7a78c6e476246f31c7fbf362

And Travis still tried to build the master branch:

```
Built from e62fad6
```

https://travis-ci.org/johncarl81/johncarl81.github.io/builds

**Comment by mwiley** [comment]
Turn on "Build only if .travis.yml present" in the settings for your repo on Travis CI.

**Comment by johncarl81** [comment]
Ah, good point.  That did the trick.  Thanks @mwiley.
I'm going to leave this open for feedback from @jirutka

**Comment by jirutka** [comment]
> What do you think about adding the .nojekyll file to the generated site directory?

This wouldn’t work, Travis doesn’t work with `.nojekyll` file at all. This is useful only to prevent GitHub Pages from building the content using Jekyll.

> Turn on "Build only if .travis.yml present" in the settings for your repo on Travis CI.

This is already described in readme, it’s step 5.3. :smirk_cat:

**Comment by johncarl81** [comment]
Make sense :+1: I should have read the README closer.  Thanks for looking @jirutka.
