### ISSUE TITLE
Better default deploy branch option

### ISSUE THREAD

**Issue by razor-x** [jirutka/rake-jekyll#9]
For `username.github.io` repos, the master branch is used for serving to GitHub Pages. To auto-detect this I'm using:

``` ruby
t.deploy_branch = -> {
  t.remote_url.match(/github\.io\.git$/) ? 'master' : 'gh-pages'
}
```

**Comment by razor-x** [comment]
Actually, to handle the case of forking a user repo, we need

``` ruby
t.deploy_branch = -> {
  user = ENV['TRAVIS_REPO_SLUG'].to_s.split('/').first
  t.remote_url.match(%r{(:|/)#{user}\.github\.io\.git$}) ? 'master' : 'gh-pages'
}
```

**Comment by jirutka** [comment]
Why `/github\.io\.git$/` isn’t sufficient?

**Comment by razor-x** [comment]
The obvious scenario I came up with is if you fork someone's io repo, then it will still match that pattern but since the username in the repo name is not yours, it will serve from the gh-pages branch.

For example, if I fork `them/them.github.io` to `me/them.github.io`, then `me/them.github.io` needs to deploy to the gh-pages branch.

**Comment by jirutka** [comment]
Ah, you’re right. By the way, when the generated content is in the master branch, what’s the source branch?

**Comment by razor-x** [comment]
I don't think GitHub has the concept of a "source branch". They just designate a special branch to be the one to serve content from (they run Jekyll on that unless you add `.nojekyll`). How stuff ends up in that branch is up to us. That's one of the reasons I originally submitted #7.

**Comment by adfernandes** [comment]
:+1:

**Comment by razor-x** [comment]
Any chance you can add this for v1.1.0?
